import Header from "./components/Header";
import SearchSideBar from "./components/SearchSideBar";
import RestaurantCard from "./components/RestaurantCard";
import { Metadata } from "next";
import { PrismaClient } from "@/prisma/generated/prisma/client";

export const metadata: Metadata = {
    title: "Search | OpenTables",
    description: "Generated by create next app",
};

const prisma = new PrismaClient();

const fetchRestaurantsByCity = (city: string | undefined) => {

    const select = {
        id: true,
        name: true,
        price: true,
        main_image: true,
        cuisine: true,
        location: true,
        slug: true
    }

    if (!city) return prisma.restaurant.findMany({ select });

    return prisma.restaurant.findMany({
        where: {
            location: {
                name: {
                    equals: city.toLowerCase()
                }
            }
        },
        select,
    });
}

export default async function Search({ searchParams }: { searchParams: { city: string } }) {
    const { city } = await searchParams;

    const restaurants = await fetchRestaurantsByCity(city);
    return (
        <>
            <Header />
            <div className="flex py-4 m-auto w-2/3 justify-between items-start">
                <SearchSideBar />
                <div className="w-5/6">
                    {restaurants.length ? <RestaurantCard /> : <p>Sorry, we found no restaurant in this area</p>}
                </div>
            </div>
        </>
    );
}