import { Metadata } from "next";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Restaurant",
  description: "Generated by create next app",
};
type Params = Promise<{ slug: string }>

export default async function RestaurantLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode,
  params: { slug: string }
}>) {

  const { slug } = await params;
  console.log(slug)

  return (
    <main>
      <Header name={slug} />
      <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
        {children}
      </div>
    </main>
  );
}