import RestaurantNavBar from "../components/RestaurantNavBar";
import Menu from "../components/Menu";
import { Metadata } from "next";
import { PrismaClient } from "@/prisma/generated/prisma/client";


const prisma = new PrismaClient();

const fetchRestaurantMenu = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug
    },
    select: {
      items: true
    }
  });

  if (!restaurant) {
    throw new Error();
  }
  return restaurant.items;
}

export const metadata: Metadata = {
  title: "Menu | Restaurant",
  description: "Generated by create next app",
};

export default async function RestaurantMenu({ params }: { params: { slug: string } }) {

  const { slug } = await params;
  const menu = await fetchRestaurantMenu(slug);
  return (
    <>
      <div className="bg-white w-[100%] rounded p-3 shadow">
        <RestaurantNavBar slug={slug} />
        <Menu menu={menu} />
      </div>
    </>
  );
}